"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    // 20 questions per checkpoint: 5A + 5B + 5C + 3D + 2E = 20
    const questions = [
      // ====== CHECKPOINT 1: Section A (Match - 5 questions) ======
      {
        checkpoint_id: "checkpoint-1",
        section: "A",
        question_type: "match",
        content: JSON.stringify({
          instruction: "Choose the correct answer",
          question: "What do you do every morning?",
          options: [
            { letter: "A", text: "I wake up and eat breakfast." },
            { letter: "B", text: "I go to sleep." },
            { letter: "C", text: "I watch TV." },
            { letter: "D", text: "I play football." },
          ],
        }),
        correct_answer: JSON.stringify({ selected: "A" }),
        score: 1,
        display_order: 1,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-1",
        section: "A",
        question_type: "match",
        content: JSON.stringify({
          instruction: "Choose the correct answer",
          question: "Where is the school?",
          options: [
            { letter: "A", text: "It is next to the park." },
            { letter: "B", text: "It is in the kitchen." },
            { letter: "C", text: "It is under the bed." },
            { letter: "D", text: "It is in the garden." },
          ],
        }),
        correct_answer: JSON.stringify({ selected: "A" }),
        score: 1,
        display_order: 2,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-1",
        section: "A",
        question_type: "match",
        content: JSON.stringify({
          instruction: "Choose the correct answer",
          question: "What time do you usually go to bed?",
          options: [
            { letter: "A", text: "I go to bed at 10 PM." },
            { letter: "B", text: "I go to school at 10 PM." },
            { letter: "C", text: "I eat breakfast at 10 PM." },
            { letter: "D", text: "I play games at 10 PM." },
          ],
        }),
        correct_answer: JSON.stringify({ selected: "A" }),
        score: 1,
        display_order: 3,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-1",
        section: "A",
        question_type: "match",
        content: JSON.stringify({
          instruction: "Choose the correct answer",
          question: "How was your weekend?",
          options: [
            { letter: "A", text: "It was great, thanks!" },
            { letter: "B", text: "It is Monday today." },
            { letter: "C", text: "I am at home." },
            { letter: "D", text: "The weather is sunny." },
          ],
        }),
        correct_answer: JSON.stringify({ selected: "A" }),
        score: 1,
        display_order: 4,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-1",
        section: "A",
        question_type: "match",
        content: JSON.stringify({
          instruction: "Choose the correct answer",
          question: "Do you like playing football?",
          options: [
            { letter: "A", text: "Yes, I do. It is fun!" },
            { letter: "B", text: "The ball is round." },
            { letter: "C", text: "Three players joined." },
            { letter: "D", text: "I read a book." },
          ],
        }),
        correct_answer: JSON.stringify({ selected: "A" }),
        score: 1,
        display_order: 5,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },

      // ====== CHECKPOINT 1: Section B (Listen & Write - 5 questions) ======
      {
        checkpoint_id: "checkpoint-1",
        section: "B",
        question_type: "listen_write",
        content: JSON.stringify({
          instruction: "Listen, choose the picture, then write the word",
          audioText: "basketball",
          options: [
            { letter: "A", image: "soccer" },
            { letter: "B", image: "basketball" },
          ],
        }),
        correct_answer: JSON.stringify({ selected: "B", written: "basketball" }),
        score: 1,
        display_order: 1,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-1",
        section: "B",
        question_type: "listen_write",
        content: JSON.stringify({
          instruction: "Listen, choose the picture, then write the word",
          audioText: "a scooter",
          options: [
            { letter: "A", image: "bicycle" },
            { letter: "B", image: "scooter" },
          ],
        }),
        correct_answer: JSON.stringify({ selected: "B", written: "a scooter" }),
        score: 1,
        display_order: 2,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-1",
        section: "B",
        question_type: "listen_write",
        content: JSON.stringify({
          instruction: "Listen, choose the picture, then write the word",
          audioText: "tape",
          options: [
            { letter: "A", image: "tape" },
            { letter: "B", image: "glue" },
          ],
        }),
        correct_answer: JSON.stringify({ selected: "A", written: "tape" }),
        score: 1,
        display_order: 3,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-1",
        section: "B",
        question_type: "listen_write",
        content: JSON.stringify({
          instruction: "Listen, choose the picture, then write the word",
          audioText: "rubber bands",
          options: [
            { letter: "A", image: "rubber bands" },
            { letter: "B", image: "pencils" },
          ],
        }),
        correct_answer: JSON.stringify({ selected: "A", written: "rubber bands" }),
        score: 1,
        display_order: 4,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-1",
        section: "B",
        question_type: "listen_write",
        content: JSON.stringify({
          instruction: "Listen, choose the picture, then write the word",
          audioText: "across from",
          options: [
            { letter: "A", image: "arrow-right" },
            { letter: "B", image: "opposite" },
          ],
        }),
        correct_answer: JSON.stringify({ selected: "B", written: "across from" }),
        score: 1,
        display_order: 5,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },

      // ====== CHECKPOINT 1: Section C (Fill in the Blank - 5 questions) ======
      {
        checkpoint_id: "checkpoint-1",
        section: "C",
        question_type: "fill_blank",
        content: JSON.stringify({
          instruction: "Choose the correct words to complete the dialogue",
          lineA: "Hi, I'm Scott. What's ___?",
          lineB: "I'm ___. Nice to meet you!",
          blanks: [
            {
              id: "a1",
              line: "A",
              options: ["your name", "you name", "name your", "my name"],
            },
            {
              id: "b1",
              line: "B",
              options: ["Kate", "your name", "Scott", "fine"],
            },
          ],
        }),
        correct_answer: JSON.stringify({
          answers: { a1: "your name", b1: "Kate" },
        }),
        score: 1,
        display_order: 1,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-1",
        section: "C",
        question_type: "fill_blank",
        content: JSON.stringify({
          instruction: "Choose the correct words to complete the dialogue",
          lineA: "Hello! ___ are you?",
          lineB: "I'm ___, thanks!",
          blanks: [
            {
              id: "a1",
              line: "A",
              options: ["How", "What", "Where", "When"],
            },
            {
              id: "b1",
              line: "B",
              options: ["fine", "Kate", "cold", "school"],
            },
          ],
        }),
        correct_answer: JSON.stringify({
          answers: { a1: "How", b1: "fine" },
        }),
        score: 1,
        display_order: 2,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-1",
        section: "C",
        question_type: "fill_blank",
        content: JSON.stringify({
          instruction: "Choose the correct words to complete the dialogue",
          lineA: "Hi, Anna! This is my ___ Sarah.",
          lineB: "___, Anna!",
          blanks: [
            {
              id: "a1",
              line: "A",
              options: ["friend", "ruler", "teacher", "library"],
            },
            {
              id: "b1",
              line: "B",
              options: ["Nice to meet you", "How are you", "Goodbye", "Hello"],
            },
          ],
        }),
        correct_answer: JSON.stringify({
          answers: { a1: "friend", b1: "Nice to meet you" },
        }),
        score: 1,
        display_order: 3,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-1",
        section: "C",
        question_type: "fill_blank",
        content: JSON.stringify({
          instruction: "Choose the correct words to complete the dialogue",
          lineA: "Where ___ you yesterday?",
          lineB: "I was ___ the library.",
          blanks: [
            {
              id: "a1",
              line: "A",
              options: ["were", "was", "are", "is"],
            },
            {
              id: "b1",
              line: "B",
              options: ["at", "in", "on", "to"],
            },
          ],
        }),
        correct_answer: JSON.stringify({
          answers: { a1: "were", b1: "at" },
        }),
        score: 1,
        display_order: 4,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-1",
        section: "C",
        question_type: "fill_blank",
        content: JSON.stringify({
          instruction: "Choose the correct words to complete the dialogue",
          lineA: "Do you ___ a ruler?",
          lineB: "Yes, I ___ one.",
          blanks: [
            {
              id: "a1",
              line: "A",
              options: ["have", "has", "had", "having"],
            },
            {
              id: "b1",
              line: "B",
              options: ["have", "has", "had", "having"],
            },
          ],
        }),
        correct_answer: JSON.stringify({
          answers: { a1: "have", b1: "have" },
        }),
        score: 1,
        display_order: 5,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },

      // ====== CHECKPOINT 1: Section D (Unscramble - 3 questions) ======
      {
        checkpoint_id: "checkpoint-1",
        section: "D",
        question_type: "unscramble",
        content: JSON.stringify({
          instruction: "Arrange the words to make a correct sentence",
          scrambled: ["cold", "was", "it"],
          image: "snow",
        }),
        correct_answer: JSON.stringify({ answer: "it was cold" }),
        score: 1,
        display_order: 1,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-1",
        section: "D",
        question_type: "unscramble",
        content: JSON.stringify({
          instruction: "Arrange the words to make a correct sentence",
          scrambled: ["ruler", "a", "have", "I"],
          image: "ruler",
        }),
        correct_answer: JSON.stringify({ answer: "i have a ruler" }),
        score: 1,
        display_order: 2,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-1",
        section: "D",
        question_type: "unscramble",
        content: JSON.stringify({
          instruction: "Arrange the words to make a correct sentence",
          scrambled: ["she", "does", "live", "where"],
          image: "house",
        }),
        correct_answer: JSON.stringify({ answer: "where does she live" }),
        score: 1,
        display_order: 3,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },

      // ====== CHECKPOINT 1: Section E (Read & Speak - 2 questions) ======
      {
        checkpoint_id: "checkpoint-1",
        section: "E",
        question_type: "read_speak",
        content: JSON.stringify({
          instruction: "Read the sentence and speak it clearly",
          sentence: "I wake up at six o'clock every morning.",
          hint: "wake up",
        }),
        correct_answer: JSON.stringify({ confirmed: true }),
        score: 1,
        display_order: 1,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-1",
        section: "E",
        question_type: "read_speak",
        content: JSON.stringify({
          instruction: "Read the sentence and speak it clearly",
          sentence: "The school is next to the park.",
          hint: "next to",
        }),
        correct_answer: JSON.stringify({ confirmed: true }),
        score: 1,
        display_order: 2,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },

      // ====== CHECKPOINT 2: Section A (Match - 5 questions) ======
      {
        checkpoint_id: "checkpoint-2",
        section: "A",
        question_type: "match",
        content: JSON.stringify({
          instruction: "Choose the correct answer",
          question: "What is your mother doing now?",
          options: [
            { letter: "A", text: "She is cooking dinner." },
            { letter: "B", text: "She goes to school." },
            { letter: "C", text: "She played football." },
            { letter: "D", text: "She will eat." },
          ],
        }),
        correct_answer: JSON.stringify({ selected: "A" }),
        score: 1,
        display_order: 1,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-2",
        section: "A",
        question_type: "match",
        content: JSON.stringify({
          instruction: "Choose the correct answer",
          question: "Where did you go last weekend?",
          options: [
            { letter: "A", text: "I went to the beach." },
            { letter: "B", text: "I go to the park." },
            { letter: "C", text: "I am at home." },
            { letter: "D", text: "I will visit my grandma." },
          ],
        }),
        correct_answer: JSON.stringify({ selected: "A" }),
        score: 1,
        display_order: 2,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-2",
        section: "A",
        question_type: "match",
        content: JSON.stringify({
          instruction: "Choose the correct answer",
          question: "How many apples are there?",
          options: [
            { letter: "A", text: "There are five apples." },
            { letter: "B", text: "There is one apple." },
            { letter: "C", text: "There are ten apples." },
            { letter: "D", text: "There are no apples." },
          ],
        }),
        correct_answer: JSON.stringify({ selected: "A" }),
        score: 1,
        display_order: 3,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-2",
        section: "A",
        question_type: "match",
        content: JSON.stringify({
          instruction: "Choose the correct answer",
          question: "What is the weather like today?",
          options: [
            { letter: "A", text: "It is sunny and warm." },
            { letter: "B", text: "It is cold and snowy." },
            { letter: "C", text: "It is rainy." },
            { letter: "D", text: "It is windy." },
          ],
        }),
        correct_answer: JSON.stringify({ selected: "A" }),
        score: 1,
        display_order: 4,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-2",
        section: "A",
        question_type: "match",
        content: JSON.stringify({
          instruction: "Choose the correct answer",
          question: "Who is your best friend?",
          options: [
            { letter: "A", text: "It is Nam. He is kind." },
            { letter: "B", text: "She is my teacher." },
            { letter: "C", text: "He plays soccer." },
            { letter: "D", text: "I have many friends." },
          ],
        }),
        correct_answer: JSON.stringify({ selected: "A" }),
        score: 1,
        display_order: 5,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },

      // ====== CHECKPOINT 2: Section B (Listen & Write - 5 questions) ======
      {
        checkpoint_id: "checkpoint-2",
        section: "B",
        question_type: "listen_write",
        content: JSON.stringify({
          instruction: "Listen, choose the picture, then write the word",
          audioText: "sandwich",
          options: [
            { letter: "A", image: "sandwich" },
            { letter: "B", image: "hamburger" },
          ],
        }),
        correct_answer: JSON.stringify({ selected: "A", written: "sandwich" }),
        score: 1,
        display_order: 1,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-2",
        section: "B",
        question_type: "listen_write",
        content: JSON.stringify({
          instruction: "Listen, choose the picture, then write the word",
          audioText: "raining",
          options: [
            { letter: "A", image: "sunny" },
            { letter: "B", image: "raining" },
          ],
        }),
        correct_answer: JSON.stringify({ selected: "B", written: "raining" }),
        score: 1,
        display_order: 2,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-2",
        section: "B",
        question_type: "listen_write",
        content: JSON.stringify({
          instruction: "Listen, choose the picture, then write the word",
          audioText: "swimming",
          options: [
            { letter: "A", image: "running" },
            { letter: "B", image: "swimming" },
          ],
        }),
        correct_answer: JSON.stringify({ selected: "B", written: "swimming" }),
        score: 1,
        display_order: 3,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-2",
        section: "B",
        question_type: "listen_write",
        content: JSON.stringify({
          instruction: "Listen, choose the picture, then write the word",
          audioText: "library",
          options: [
            { letter: "A", image: "library" },
            { letter: "B", image: "classroom" },
          ],
        }),
        correct_answer: JSON.stringify({ selected: "A", written: "library" }),
        score: 1,
        display_order: 4,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-2",
        section: "B",
        question_type: "listen_write",
        content: JSON.stringify({
          instruction: "Listen, choose the picture, then write the word",
          audioText: "hospital",
          options: [
            { letter: "A", image: "school" },
            { letter: "B", image: "hospital" },
          ],
        }),
        correct_answer: JSON.stringify({ selected: "B", written: "hospital" }),
        score: 1,
        display_order: 5,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },

      // ====== CHECKPOINT 2: Section C (Fill in the Blank - 5 questions) ======
      {
        checkpoint_id: "checkpoint-2",
        section: "C",
        question_type: "fill_blank",
        content: JSON.stringify({
          instruction: "Choose the correct words to complete the dialogue",
          lineA: "I ___ to school every ___.",
          lineB: "That is great!",
          blanks: [
            {
              id: "a1",
              line: "A",
              options: ["go", "went", "going", "goes"],
            },
            {
              id: "a2",
              line: "A",
              options: ["day", "park", "book", "morning"],
            },
          ],
        }),
        correct_answer: JSON.stringify({
          answers: { a1: "go", a2: "day" },
        }),
        score: 1,
        display_order: 1,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-2",
        section: "C",
        question_type: "fill_blank",
        content: JSON.stringify({
          instruction: "Choose the correct words to complete the dialogue",
          lineA: "The cat is ___ the table.",
          lineB: "I ___ it!",
          blanks: [
            {
              id: "a1",
              line: "A",
              options: ["on", "in", "under", "behind"],
            },
            {
              id: "b1",
              line: "B",
              options: ["see", "saw", "watch", "read"],
            },
          ],
        }),
        correct_answer: JSON.stringify({
          answers: { a1: "on", b1: "see" },
        }),
        score: 1,
        display_order: 2,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-2",
        section: "C",
        question_type: "fill_blank",
        content: JSON.stringify({
          instruction: "Choose the correct words to complete the dialogue",
          lineA: "Tom has two ___.",
          lineB: "What ___ they?",
          blanks: [
            {
              id: "a1",
              line: "A",
              options: ["dogs", "dog", "a dog", "dogs are"],
            },
            {
              id: "b1",
              line: "B",
              options: ["are", "is", "am", "was"],
            },
          ],
        }),
        correct_answer: JSON.stringify({
          answers: { a1: "dogs", b1: "are" },
        }),
        score: 1,
        display_order: 3,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-2",
        section: "C",
        question_type: "fill_blank",
        content: JSON.stringify({
          instruction: "Choose the correct words to complete the dialogue",
          lineA: "What ___ you do yesterday?",
          lineB: "I ___ soccer.",
          blanks: [
            {
              id: "a1",
              line: "A",
              options: ["did", "do", "does", "doing"],
            },
            {
              id: "b1",
              line: "B",
              options: ["played", "play", "plays", "playing"],
            },
          ],
        }),
        correct_answer: JSON.stringify({
          answers: { a1: "did", b1: "played" },
        }),
        score: 1,
        display_order: 4,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-2",
        section: "C",
        question_type: "fill_blank",
        content: JSON.stringify({
          instruction: "Choose the correct words to complete the dialogue",
          lineA: "My birthday is ___ March.",
          lineB: "That is ___!",
          blanks: [
            {
              id: "a1",
              line: "A",
              options: ["in", "on", "at", "to"],
            },
            {
              id: "b1",
              line: "B",
              options: ["soon", "late", "under", "yesterday"],
            },
          ],
        }),
        correct_answer: JSON.stringify({
          answers: { a1: "in", b1: "soon" },
        }),
        score: 1,
        display_order: 5,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },

      // ====== CHECKPOINT 2: Section D (Unscramble - 3 questions) ======
      {
        checkpoint_id: "checkpoint-2",
        section: "D",
        question_type: "unscramble",
        content: JSON.stringify({
          instruction: "Arrange the words to make a correct sentence",
          scrambled: ["play", "football", "We", "often"],
          image: "football",
        }),
        correct_answer: JSON.stringify({ answer: "we often play football" }),
        score: 1,
        display_order: 1,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-2",
        section: "D",
        question_type: "unscramble",
        content: JSON.stringify({
          instruction: "Arrange the words to make a correct sentence",
          scrambled: ["my", "is", "name", "Nam"],
          image: "person",
        }),
        correct_answer: JSON.stringify({ answer: "my name is nam" }),
        score: 1,
        display_order: 2,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-2",
        section: "D",
        question_type: "unscramble",
        content: JSON.stringify({
          instruction: "Arrange the words to make a correct sentence",
          scrambled: ["like", "I", "apples", "do"],
          image: "apple",
        }),
        correct_answer: JSON.stringify({ answer: "i do like apples" }),
        score: 1,
        display_order: 3,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },

      // ====== CHECKPOINT 2: Section E (Read & Speak - 2 questions) ======
      {
        checkpoint_id: "checkpoint-2",
        section: "E",
        question_type: "read_speak",
        content: JSON.stringify({
          instruction: "Read the sentence and speak it clearly",
          sentence: "She is reading a book in the library.",
          hint: "reading",
        }),
        correct_answer: JSON.stringify({ confirmed: true }),
        score: 1,
        display_order: 1,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        checkpoint_id: "checkpoint-2",
        section: "E",
        question_type: "read_speak",
        content: JSON.stringify({
          instruction: "Read the sentence and speak it clearly",
          sentence: "They went to the beach last summer.",
          hint: "went",
        }),
        correct_answer: JSON.stringify({ confirmed: true }),
        score: 1,
        display_order: 2,
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ];

    for (const q of questions) {
      await queryInterface.insert(null, "question_checkpoints", q, {});
    }
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("question_checkpoints", null, {});
  },
};
